<a href="https://colab.research.google.com/github/jchen8000/GenerativeAI/blob/main/2_Pytorch_Basics_Math_Fundamentals/PyTorch_Basices_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.	Pytorch Basics and Math Fundamentals (Part 1)



*   2.1 Tensor and Vector
*   2.2 Tensor and Matrix
*   2.3 Dot Product
*   2.4 Softmax




In [ ]:
import torch
import torch.nn as nn

## 2.1	Tensor and Vector

In [ ]:
vector = torch.tensor([2., 3., 4.])
print("Vector:", vector)

Vector: tensor([2., 3., 4.])


In [ ]:
torch.norm(vector)

tensor(5.3852)

In [ ]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 75,  18, -59,  52,  50, -24])

In [ ]:
empty = torch.empty(3)
empty

tensor([2.6416e+11, 3.1102e-41, 1.5835e-42])

In [ ]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [ ]:
arange = torch.arange(start=0, end=5, step=1)
arange

tensor([0, 1, 2, 3, 4])

In [ ]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [ ]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

## 2.2	Tensor and Matrix

In [ ]:
A = torch.tensor([[1., 2., 3., 4.],
                  [2., 3., 4., 5.],
                  [3., 4., 5., 6.]])
A

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [3., 4., 5., 6.]])

In [ ]:
zeros = torch.zeros(3, 4)
print("zeros =", zeros)

ones = torch.ones(3, 4)
print("ones =", ones)

zeros = tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
empty = torch.empty(2, 3)
print("empty =", empty)

empty = tensor([[2.6486e+11, 3.1102e-41, 2.6464e+11],
        [3.1102e-41, 1.1210e-43, 0.0000e+00]])


In [ ]:
I = torch.eye(4)
I

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
lower_tri = torch.tril(torch.ones(5, 5))
lower_tri

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
upper_tri = torch.triu(torch.ones(5, 5))
upper_tri

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [ ]:
a = torch.tensor([[1., 2., 3., 4.],
                  [2., 3., 4., 5.],
                  [3., 4., 5., 6.]])
empty_like = torch.empty_like(a)
empty_like

tensor([[3.8416e+10, 3.1102e-41, 2.8889e+10, 3.1102e-41],
        [5.8554e+19, 4.3519e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])  # means 10% chance to get a 0, and 90% chance to get a 1.
samples = torch.multinomial(probabilities, num_samples=100, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])


In [ ]:
# concatenate two tensors
A=torch.ones(2, 3)
B=2*torch.ones(4, 3)
C=torch.cat((A,B),dim=0)
print("A= ", A)
print("B =", B)
print("C =", C)

A=  tensor([[1., 1., 1.],
        [1., 1., 1.]])
B = tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
C = tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [ ]:
a = torch.tensor([1, 3, 5, 8])
b = torch.tensor([2, 6, 7, 9])
c = torch.tensor([5, 6, 3, 2])
stacked = torch.stack([a, b, c], dim=0)
stacked

tensor([[1, 3, 5, 8],
        [2, 6, 7, 9],
        [5, 6, 3, 2]])

In [ ]:
from torch.nn.utils.rnn import pad_sequence
a = torch.tensor([1, 3, 5, 8])
b = torch.tensor([2, 7, 9])
c = torch.tensor([5, 2])
padded = pad_sequence([a, b, c], batch_first=True)
padded

tensor([[1, 3, 5, 8],
        [2, 7, 9, 0],
        [5, 2, 0, 0]])

In [ ]:
padding_mask = padded.eq(0)
padding_mask

tensor([[False, False, False, False],
        [False, False, False,  True],
        [False, False,  True,  True]])

In [ ]:
A = torch.tensor([[1., 2., 3., 4.],
                  [2., 3., 4., 5.],
                  [3., 4., 5., 6.]])
A_T = A.transpose(-2, -1)
A_T

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])

In [ ]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10., 10.])
linear = nn.Linear(4, 3, bias=True)
print(linear(sample))

tensor([-6.9280,  4.7998, -0.2741], grad_fn=<ViewBackward0>)


## 2.3 Dot Product

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
dot_product = torch.dot(a, b)
dot_product

tensor(32)

In [ ]:
print("Dot Product:", dot_product.item())

Dot Product: 32


In [ ]:
a = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
b = torch.tensor([[7,   8,  9],
                  [10, 11, 12]])
# print( a @ b )
print(torch.matmul(a, b))


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


## 2.4 Softmax

In [ ]:
logits = torch.tensor([2.0, 5.0, 3.0])
softmax = nn.functional.softmax(logits, dim=0)
print("Logits:", logits)
print("Softmax:", softmax)

Logits: tensor([2., 5., 3.])
Softmax: tensor([0.0420, 0.8438, 0.1142])


In [ ]:
a = torch.tensor([0., float('-inf')])
torch.exp(a)

tensor([1., 0.])

In [ ]:
A = torch.zeros(5, 5)
mask = torch.tril(torch.ones(5, 5))
print("mask=\n", mask)
A = A.masked_fill(mask==0, float('-inf'))
print("A=\n", A)

mask=
 tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
A=
 tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [ ]:
nn.functional.softmax(A, dim=1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000]])